# -*- coding: utf-8 -*-
"""김도은 - 205_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IzlslSkcf0Z3cGjtGrp87jz19q9QVVs
"""

print(5+2)
print(5-2)
print(5*2)
print(5/2)
print(5**2)
print(5//2)
print(5%2)

x=10%3
print(x)
y=7//3
print(y)

a=10
b=20
c=a=b*10-5/5
print(c)

x=2**3
print(x)
y=10**4
print(y)

hello='안녕'*5
print(hello)

s1="대한민국"
s2="만세"
print(s1+s2)
print(s1*5)

print("korea"+str(2021))
print(10+int("22"))
print(10+int(22.5))
print(10+int(float(22.5)))
print("korea"+2021)

x=10
x+=20
print(x)

a=5
a=a+1
print(a)
a=5
a+=1
print(a)
a-=5
print(a)
a*=2
print(a)

x=3
y=5
x*=x+y
print(x)

money = (int (input("투입한 돈:")))
price = (int (input("물건 값:")))
change = money-price
print("거스름돈:",change)
print("500원 동전의 갯수:", change/500)
print("100원 동전의 갯수:",change%500/100)

if 3<5:
  print("Hellow World")

if 3>5:
  print("Hellow World")

age=int(input("몇살입니까?"))
if age<20:
  print("학생입니다")

age=15;
if age<20:
  print("학생입니다.")
print("안녕히가세요")

print(3==5)
print(3!=5)
print(3<5)

x=4
print(1<x<5)

print(35)

country="korea"
if country == "korea":
  print("한국")

age=int(input("몇살입니까?"))
if age<20:
  print("학생입니다.")
else:
  print("성인입니다.")

password=input("암호 입력")
if password == "암호":
  print("암호이다.")
else:
  print("암호가 아니다")

num= int(input("숫자를 입력하세요:"))
if num%2==1:
  print("음수입니다")
else:
  print("양수입니다")

num1=int(input("첫번째 숫자를 입력하세요:"))
num2=int(input("두번째 숫자를 입력하세요:"))
if num1>num2:
  print(num1)
elif num1==num2:
  print("같다")
else:
  print(num2)

weekly=int(input("1(주간 근무) 또는 2(야간업무)을 입력하세요:"))
time=int(input("근무 시간을 입력해주세요:"))
money=int(time*9500)
if weekly==1:
  print(time,"시간 동안 일한 주간 급여는", money,"원 입니다.")
else:
  print(time,"시간 동안 일한 주간 급여는", money*1.5,"원 입니다.")

name=input("이름을 입력하세요:")
time=int(input("일주일간 일한 시간을 입력하세요:"))
if time>=40:
  overtime=time-40
  print("초과 시간:",overtime)
  totalmoney=((time-overtime)*12000)+((overtime*1.5)*12000)
  print(name, "님의 주급은", int(totalmoney),"입니다")
else:
  print(name, "님의 주급은", time*12000,"입니다")

